[build]
target = "x86_64-kudos.json"

[target.'x86_64-kudos']
runner = "bootimage runner"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true
json-target-spec = true
